[package]
org = "toshiba"
name = "account"
version = "0.1.0"
distribution = "2201.10.0"

[build-options]
observabilityIncluded = true

[[platform.java17.dependency]]
groupId = "mysql"
artifactId = "mysql-connector-java"
version = "8.0.25"

[environments]
DB_HOST = "${DB_HOST}"
DB_PORT = "${DB_PORT}"
DB_USERNAME = "${DB_USERNAME}"
DB_PASSWORD = "${DB_PASSWORD}"
DB_NAME = "${DB_NAME}"